//! The website's CLI reference, rendered from the clap command tree, so the
//! page lists every command, argument and flag with the same help `--help`
//! prints and cannot drift from the binary. What the page has above
//! [`MARKER`] is written by hand and kept; everything below it is rendered.
//! `make cli-reference` writes it; a test in main.rs fails when the
//! checked-in page is not what this renders.

use clap::{Arg, Command};

/// The line that starts the rendered part of the page.
pub const MARKER: &str =
    "<!-- Generated by `make cli-reference` from the clap definitions; do not edit. -->";

/// `page` with everything from [`MARKER`] on rendered again from `root`; a
/// page without the marker is all preamble.
pub fn refresh(root: &Command, page: &str) -> String {
    render(root, page.split(MARKER).next().unwrap_or_default())
}

/// The page: `preamble` (front matter and prose written by hand), then one
/// `##` section per top-level command and a `###` heading for each command
/// under it that takes arguments or is a leaf. The root's own arguments,
/// such as the global ones, come first under `## pastor`.
pub fn render(root: &Command, preamble: &str) -> String {
    let mut out = String::from(preamble.trim_end());
    out.push_str("\n\n");
    out.push_str(MARKER);
    out.push_str("\n\n");
    let name = root.get_name();
    if visible_args(root).next().is_some() {
        out.push_str(&format!("## {name}\n\n"));
        push_about(&mut out, root);
        push_args(&mut out, root);
    }
    for sub in subcommands(root) {
        let path = format!("{name} {}", sub.get_name());
        out.push_str(&format!("## {}\n\n", sub.get_name()));
        push_about(&mut out, sub);
        push_args(&mut out, sub);
        push_children(&mut out, sub, &path);
    }
    out.truncate(out.trim_end().len());
    out.push('\n');
    out
}

fn push_children(out: &mut String, cmd: &Command, path: &str) {
    for sub in subcommands(cmd) {
        let path = format!("{path} {}", sub.get_name());
        out.push_str(&format!("### {path}\n\n"));
        push_about(out, sub);
        push_args(out, sub);
        push_children(out, sub, &path);
    }
}

fn subcommands(cmd: &Command) -> impl Iterator<Item = &Command> {
    cmd.get_subcommands()
        .filter(|s| !s.is_hide_set() && s.get_name() != "help")
}

fn visible_args(cmd: &Command) -> impl Iterator<Item = &Arg> {
    cmd.get_arguments()
        .filter(|a| !a.is_hide_set() && !matches!(a.get_id().as_str(), "help" | "version"))
}

fn push_about(out: &mut String, cmd: &Command) {
    let about = cmd
        .get_long_about()
        .or(cmd.get_about())
        .map(|a| a.to_string())
        .unwrap_or_default();
    if !about.trim().is_empty() {
        out.push_str(&escape(about.trim()));
        out.push_str("\n\n");
    }
}

fn push_args(out: &mut String, cmd: &Command) {
    let args: Vec<&Arg> = visible_args(cmd).collect();
    if args.is_empty() {
        return;
    }
    out.push_str("| argument | does | default |\n|---|---|---|\n");
    for arg in args {
        let help = arg
            .get_long_help()
            .or(arg.get_help())
            .map(|h| h.to_string())
            .unwrap_or_default();
        let mut does = cell(&help);
        let values: Vec<String> = arg
            .get_possible_values()
            .iter()
            .filter(|v| !v.is_hide_set())
            .map(|v| format!("`{}`", v.get_name()))
            .collect();
        if !values.is_empty() && arg.get_action().takes_values() {
            does.push_str(&format!(" (one of {})", values.join(", ")));
        }
        if arg.is_required_set() && !arg.is_positional() {
            does.push_str(" (required)");
        }
        // A flag's default is only clap's `false`, which says nothing.
        let default: Vec<String> = arg
            .get_default_values()
            .iter()
            .filter(|_| arg.get_action().takes_values())
            .map(|v| format!("`{}`", v.to_string_lossy()))
            .collect();
        out.push_str(&format!(
            "| `{}` | {} | {} |\n",
            spelling(arg),
            does,
            default.join(", ")
        ));
    }
    out.push('\n');
}

/// How the argument is typed: `<NAME>` for a positional one, else its
/// short and long flags with the value it takes.
fn spelling(arg: &Arg) -> String {
    let value = arg
        .get_value_names()
        .and_then(|n| n.first())
        .map(|n| n.to_string())
        .unwrap_or_else(|| arg.get_id().to_string());
    if arg.is_positional() {
        return format!("<{value}>");
    }
    let mut flags = Vec::new();
    if let Some(s) = arg.get_short() {
        flags.push(format!("-{s}"));
    }
    if let Some(l) = arg.get_long() {
        flags.push(format!("--{l}"));
    }
    let mut out = flags.join(", ");
    if arg.get_action().takes_values() {
        out.push_str(&format!(" <{value}>"));
    }
    out
}

/// One table cell: the help on one line, with pipes escaped.
fn cell(text: &str) -> String {
    escape(&text.split_whitespace().collect::<Vec<_>>().join(" ")).replace('|', "\\|")
}

/// Help text as Markdown: angle brackets outside code spans become entities,
/// since the site renders raw HTML and `pane:<workspace>` would be a tag.
fn escape(text: &str) -> String {
    text.split('`')
        .enumerate()
        .map(|(i, part)| match i % 2 {
            0 => part.replace('<', "&lt;").replace('>', "&gt;"),
            _ => part.to_string(),
        })
        .collect::<Vec<_>>()
        .join("`")
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::ArgAction;

    fn sample() -> Command {
        Command::new("pastor")
            .about("run agents")
            .arg(
                Arg::new("head")
                    .long("head")
                    .value_name("DEST")
                    .help("Use this head"),
            )
            .subcommand(
                Command::new("task")
                    .about("Manage tasks")
                    .subcommand(
                        Command::new("run")
                            .about("Queue a task")
                            .long_about("Queue a task\n\nIt waits for a free machine.")
                            .arg(Arg::new("prompt").help("What to do | how").required(true))
                            .arg(
                                Arg::new("priority")
                                    .long("priority")
                                    .help("How urgent: <level> or `<level>`")
                                    .value_parser(["low", "normal"])
                                    .default_value("normal"),
                            )
                            .arg(
                                Arg::new("wide")
                                    .short('w')
                                    .long("wide")
                                    .action(ArgAction::SetTrue)
                                    .help("Wider\ntable"),
                            )
                            .arg(Arg::new("secret").long("secret").hide(true)),
                    )
                    .subcommand(Command::new("hidden").hide(true)),
            )
    }

    #[test]
    fn starts_with_the_preamble_and_says_it_is_generated() {
        let page = render(&sample(), "---\ntitle: cli\n---\nIntro.\n");
        assert!(page.starts_with("---\ntitle: cli\n---\nIntro.\n\n<!-- Generated"));
        assert!(!page.contains("\n\n\n"), "{page}");
        assert!(page.ends_with("|\n"), "{page}");
    }

    #[test]
    fn refresh_keeps_what_is_above_the_marker_and_replaces_the_rest() {
        let page = format!("Intro.\n\n{MARKER}\n\n## stale\n");
        let fresh = refresh(&sample(), &page);
        assert!(fresh.starts_with(&format!("Intro.\n\n{MARKER}\n")));
        assert!(!fresh.contains("stale"), "{fresh}");
        assert_eq!(refresh(&sample(), &fresh), fresh);
    }

    #[test]
    fn lists_every_visible_command_with_its_long_about() {
        let page = render(&sample(), "");
        assert!(page.contains("\n## pastor\n\nrun agents\n"));
        assert!(page.contains("It waits for a free machine.\n\n| argument"));
        assert!(page.contains("\n## task\n\nManage tasks\n"));
        assert!(
            page.contains(
                "\n### pastor task run\n\nQueue a task\n\nIt waits for a free machine.\n"
            )
        );
        assert!(!page.contains("hidden"), "{page}");
        assert!(!page.contains("### pastor task help"), "{page}");
    }

    #[test]
    fn lists_every_visible_argument_with_help_values_and_default() {
        let page = render(&sample(), "");
        assert!(
            page.contains("| `--head <DEST>` | Use this head |  |\n"),
            "{page}"
        );
        assert!(
            page.contains("| `<prompt>` | What to do \\| how |  |\n"),
            "{page}"
        );
        assert!(
            page.contains(
                "| `--priority <priority>` | How urgent: &lt;level&gt; or `<level>` (one of `low`, `normal`) | `normal` |\n"
            ),
            "{page}"
        );
        assert!(
            page.contains("| `-w, --wide` | Wider table |  |\n"),
            "{page}"
        );
        assert!(!page.contains("--secret"), "{page}");
        assert!(!page.contains("--help"), "{page}");
    }
}
