when:
  - event: pull_request
steps:
  - name: check
    image: rust:1-slim
    commands:
      - apt-get update -qq
      - apt-get install -qq -y --no-install-recommends pkg-config libsqlite3-dev make git
      - sleep 1800
